baseurl = "http://ilaericky.it/"
languageCode = "en-us"
title = "Ila e Ricky"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
canonifyurls = true
theme = "casper"

[params]
  description = "Ci siamo sposati il 25 Giugno 2016!"
  cover = "images/cover.png"
  author = "Riccardo Tribbia e Ilaria Bariletti"
  authorlocation = "Besenello, Italy"
  authorwebsite = "http://ilaericky.it"
  bio = "Ci siamo sposati davvero! Il 25 giugno 2016"
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-38837728-2"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..." 
  # githubName = "vjeantet"
  # twitterName = "vjeantet"
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Ila e Ricky"
  weight = 1
  identifier = "ilaericky"
  url = "/"

[[menu.main]]
  name = "Itinerario viaggio"
  weight = 2
  identifier = "itinerario"
  url = "/itinerario"

[[menu.main]]
  name = "Scrivici!"
  weight = 3
  identifier = "scrivici"
  url = "/scrivici"

[[menu.main]]
  name = "Lista viaggio"
  weight = 4
  identifier = "lista-viaggio"
  url = "/lista-viaggio"

[[menu.main]]
  name = "App foto"
  weight = 5
  identifier = "app-foto"
  url = "/app-foto"
  